### ISSUE TITLE
skill.json apis endpoint uri

### ISSUE THREAD

**Issue by danagibson** [alexa-labs/skill-sample-nodejs-task-buddy#2]
In attempting to deploy the skill I get an error that the uri in skill.json endpoint does not match the regex for its definition. I change it to meet the regex and I get that the trigger setting is invalid. Is that entry referring to a function that has been created outside of the skill definition? What am I missing?

**Comment by rmtuckerphx** [comment]
In the `skill.json` file, have you tried removing the line that has "sourceDir" and make sure your "uri" is a Lambda ARN?

```
    "apis": {
      "custom": {
        "endpoint": {
          "sourceDir": "lambda",
          "uri": "ask-custom-task-buddy"
        },
        "tasks": [
          {
```

**Comment by danagibson** [comment]
Yes....didn't work...I'll try it again...I've taken out the sourceDir from the beginning because that's the first error I got. I used the arn from skill-sample-alexa-for-apps. I'll try it again.

**Comment by danagibson** [comment]
Oh...but when I deployed that other sample...I was told that I didn't have authorization to use it and apply at design.alexa. When I use it in task buddy I get that the trigger setting is invalid.

**Comment by danagibson** [comment]
By the way...how would I decide what arn to use in the manifest? Is this a lambda function that is pre-defined and know by someone other than me?

**Comment by danagibson** [comment]
[Error]: {
  "skill": {
    "resources": [
      {
        "action": "CREATE",
        "errors": [
          {
            "message": "The trigger setting for the Lambda arn:aws:lambda:us-east-1:910734725388:function:5e6f0f3d-9dd6-49fa-ba08-2b7dfa13f1e1:Release_0 is invalid."
          }
        ],
        "name": "Manifest",
        "status": "FAILED"
      }
    ]
  },
  "status": "FAILED"
}

**Comment by danagibson** [comment]
Original message after taking out sourceDir:

C:\Users\dgibs\github\skill-sample-nodejs-task-buddy>ask deploy
==================== Deploy Skill Metadata ====================
[Error]: {
  "skill": {
    "resources": [
      {
        "action": "CREATE",
        "errors": [
          {
            "message": "String instance with value \"ask-custom-task-buddy\" at property path \"$.manifest.apis.custom.endpoint.uri\" does not match the regular expression: \"^(arn|https://)\"."
          }
        ],
        "name": "Manifest",
        "status": "FAILED"
      }
    ]
  },
  "status": "FAILED"
}

**Comment by danagibson** [comment]
After a conversation with Mark I resolved the problem by inferring a number of things from an obtuse discussion.

**Comment by chandlerjwang** [comment]
There are 2 ways to resolve the issue:

1. remove the "endpoint" object all together and the ask sdk will create a new lambda using your default profile:
```
    "apis": {
      "custom": {
        "tasks": [
          {
```

2. Replace the "url" field with a valid Lambda ARN value

Hope this helps!

**Comment by danagibson** [comment]
Chandler...that helps immensely. The former is probably how the sample should have been set up and explained.

**Comment by chandlerjwang** [comment]
Thank you for bringing this up, @danagibson ! We've merged the fix and updated the instructions.

**Comment by danagibson** [comment]
Chandler:

Thank you….you have handled this exactly as it should have been. I asked a number of people what was going on and didn’t get any help before you became involved. I had already figured out a way to handle it when I finally went and created a function

On Lambda…it became obvious what the issue was.

Thanks again,

Dana
